### ISSUE TITLE
avr-mcu.ads missing for atmega32u4, atmega32u6

### ISSUE THREAD

**Issue by Fabien-Chouteau** [RREE/AVRAda_MCU#1]
Hi @RREE,

I was trying to use the `atmega32u4` and got a compiler error. `avr-mcu.ads` might also be missing for MCUs others I didn't check all of them.

**Comment by RREE** [comment]
The package renamings were missing almost everywhere. Should be fixed in v2.2.0

**Comment by RREE** [comment]
missing packages generated
